import type { CSSResultGroup, PropertyValues, TemplateResult } from "lit";
import { LitElement } from "lit";
import type { LocalizeKeys } from "../../common/translations/localize";
import "../../components/ha-button";
import "../../components/ha-dropdown";
import "../../components/ha-dropdown-item";
import "../../components/ha-icon";
import "../../components/ha-icon-button";
import "../../components/ha-icon-button-arrow-next";
import "../../components/ha-icon-button-arrow-prev";
import "../../components/ha-menu-button";
import "../../components/ha-svg-icon";
import "../../components/ha-tab-group";
import "../../components/ha-tab-group-tab";
import "../../components/ha-tooltip";
import type { HomeAssistant, PanelInfo } from "../../types";
import type { Lovelace } from "./types";
import "./views/hui-view";
import "./views/hui-view-background";
import "./views/hui-view-container";
export interface ExtraActionItem {
    icon: string;
    labelKey: LocalizeKeys;
    action: () => void;
}
declare class HUIRoot extends LitElement {
    panel?: PanelInfo;
    hass: HomeAssistant;
    lovelace?: Lovelace;
    narrow: boolean;
    route?: {
        path: string;
        prefix: string;
    };
    extraActionItems?: ExtraActionItem[];
    noEdit: boolean;
    backButton: boolean;
    backPath?: string;
    private _curView?;
    private _resourceMode;
    private _configChangedByUndo;
    private _viewCache;
    private _viewScrollPositions;
    private _restoreScroll;
    private _undoRedoController;
    private _conversation;
    private _renderActionItems;
    protected render(): TemplateResult;
    private _handleWindowScroll;
    private _locationChanged;
    private _handlePopState;
    private _isVisible;
    private _clearParam;
    protected firstUpdated(changedProps: PropertyValues<this>): void;
    connectedCallback(): void;
    disconnectedCallback(): void;
    private _handleUrlChanged;
    protected willUpdate(changedProperties: PropertyValues<this>): void;
    protected updated(changedProperties: PropertyValues<this>): void;
    private get config();
    private get _yamlMode();
    private get _editMode();
    private get _viewRoot();
    private _handleRefresh;
    private _handleReloadResources;
    private _showQuickBar;
    private _goBack;
    private _addDevice;
    private _createAutomation;
    private _createArea;
    private _addPerson;
    private _handleRawEditor;
    private _handleManageDashboards;
    private _handleManageResources;
    private _handleUnusedEntities;
    private _showVoiceCommandDialog;
    private _enableEditMode;
    private _editModeDisable;
    private _editDashboard;
    private _navigateToView;
    private _editView;
    private _moveViewLeft;
    private _moveViewRight;
    private _addView;
    private _handleViewSelected;
    private _cleanupViewCache;
    private _selectView;
    private _applyUndoRedo;
    private _undo;
    private _redo;
    private _handleSubItemSelect;
    private _handleOverflowItemSelect;
    static get styles(): CSSResultGroup;
}
declare global {
    interface HTMLElementTagNameMap {
        "hui-root": HUIRoot;
    }
}
export {};
