import "@home-assistant/webawesome/dist/components/divider/divider";
import type { HassEntity } from "home-assistant-js-websocket";
import type { CSSResultGroup, PropertyValues } from "lit";
import { LitElement } from "lit";
import "../../../components/data-table/ha-data-table-labels";
import "../../../components/ha-alert";
import "../../../components/ha-check-list-item";
import "../../../components/ha-dropdown";
import "../../../components/ha-dropdown-item";
import "../../../components/ha-filter-devices";
import "../../../components/ha-filter-domains";
import "../../../components/ha-filter-floor-areas";
import "../../../components/ha-filter-integrations";
import "../../../components/ha-filter-labels";
import "../../../components/ha-filter-states";
import "../../../components/ha-filter-voice-assistants";
import "../../../components/ha-icon";
import "../../../components/ha-icon-button";
import "../../../components/ha-sub-menu";
import "../../../components/ha-svg-icon";
import "../../../components/ha-tooltip";
import type { CloudStatus } from "../../../data/cloud";
import type { EntityRegistryEntry } from "../../../data/entity/entity_registry";
import type { LabelRegistryEntry } from "../../../data/label/label_registry";
import "../../../layouts/hass-loading-screen";
import "../../../layouts/hass-tabs-subpage-data-table";
import type { HomeAssistant, Route } from "../../../types";
import "../integrations/ha-integration-overflow-menu";
export interface StateEntity extends Omit<EntityRegistryEntry, "id" | "unique_id"> {
    readonly?: boolean;
    selectable?: boolean;
    id?: string;
    unique_id?: string;
}
export interface EntityRow extends StateEntity {
    entity?: HassEntity;
    unavailable: boolean;
    restored: boolean;
    status: string | undefined;
    area?: string;
    device?: string;
    device_full?: string;
    localized_platform: string;
    domain: string;
    label_entries: LabelRegistryEntry[];
    assistants: string[];
    assistants_sortable_key: string | undefined;
    enabled: string;
    visible: string;
    available: string;
}
export declare class HaConfigEntities extends LitElement {
    hass: HomeAssistant;
    isWide: boolean;
    narrow: boolean;
    route: Route;
    cloudStatus?: CloudStatus;
    private _entries?;
    private _subEntries?;
    private _manifests?;
    _entities: EntityRegistryEntry[];
    private _entitiesWithoutUniqueId;
    private _exposedEntities?;
    private _filter;
    private _searchParms;
    private _filters;
    private _filteredItems;
    private _selected;
    private _expandedFilter?;
    _labels?: LabelRegistryEntry[];
    private _entitySources?;
    private _activeSorting?;
    private _activeGrouping?;
    private _activeCollapsed?;
    private _activeColumnOrder?;
    private _activeHiddenColumns?;
    private get _availableAssistants();
    private _dataTable;
    connectedCallback(): void;
    disconnectedCallback(): void;
    private _locationChanged;
    private _popState;
    private _states;
    private _columns;
    private _filteredEntitiesAndDomains;
    private _renderLabelItems;
    protected render(): import("lit-html").TemplateResult<1>;
    private _filterExpanded;
    private _filterChanged;
    protected firstUpdated(): void;
    private _setFiltersFromUrl;
    private _clearFilter;
    private _fetchExposedEntities;
    private _getExposedEntityVoiceAssistantIds;
    private _getExposedEntitySettingsAsOptions;
    willUpdate(changedProps: PropertyValues): void;
    private _handleSearchChange;
    private _handleSelectionChanged;
    private _enableSelected;
    private _disableSelected;
    private _hideSelected;
    private _unhideSelected;
    private _handleBulkLabel;
    private _bulkLabel;
    private _bulkCreateLabel;
    private _restoreEntityIdSelected;
    private _removeSelected;
    private _clearSelection;
    private _openEditEntry;
    private _loadConfigEntries;
    private _loadSubEntries;
    private _addDevice;
    private _handleSortingChanged;
    private _handleGroupingChanged;
    private _handleCollapseChanged;
    private _handleColumnsChanged;
    private _handleBulkAction;
    static get styles(): CSSResultGroup;
}
declare global {
    interface HTMLElementTagNameMap {
        "ha-config-entities": HaConfigEntities;
    }
}
