import "@home-assistant/webawesome/dist/components/divider/divider";
import type { CSSResultGroup, PropertyValues, TemplateResult } from "lit";
import { LitElement } from "lit";
import "../../../components/data-table/ha-data-table-labels";
import "../../../components/entity/ha-battery-icon";
import "../../../components/ha-alert";
import "../../../components/ha-button";
import "../../../components/ha-check-list-item";
import "../../../components/ha-dropdown";
import "../../../components/ha-dropdown-item";
import "../../../components/ha-filter-devices";
import "../../../components/ha-filter-floor-areas";
import "../../../components/ha-filter-integrations";
import "../../../components/ha-filter-labels";
import "../../../components/ha-filter-states";
import "../../../components/ha-icon-button";
import "../../../components/ha-sub-menu";
import type { ConfigEntry } from "../../../data/config_entries";
import type { EntityRegistryEntry } from "../../../data/entity/entity_registry";
import type { IntegrationManifest } from "../../../data/integration";
import type { LabelRegistryEntry } from "../../../data/label/label_registry";
import "../../../layouts/hass-tabs-subpage-data-table";
import type { HomeAssistant, Route } from "../../../types";
import "../integrations/ha-integration-overflow-menu";
export declare class HaConfigDeviceDashboard extends LitElement {
    hass: HomeAssistant;
    narrow: boolean;
    isWide: boolean;
    entries: ConfigEntry[];
    private _subEntries?;
    entities: EntityRegistryEntry[];
    manifests: IntegrationManifest[];
    route: Route;
    private _searchParms;
    private _selected;
    private _selectedCanDelete;
    private _dataTable;
    private _filter;
    private _filters;
    private _expandedFilter?;
    _labels?: LabelRegistryEntry[];
    private _activeSorting?;
    private _activeGrouping?;
    private _activeCollapsed?;
    private _activeColumnOrder?;
    private _activeHiddenColumns?;
    private _sizeController;
    private _ignoreLocationChange;
    connectedCallback(): void;
    disconnectedCallback(): void;
    private _locationChanged;
    private _popState;
    private _states;
    willUpdate(changedProps: PropertyValues): void;
    private _setFiltersFromUrl;
    private _filterLabel;
    private _clearFilter;
    private _devicesAndFilterDomains;
    private _columns;
    private _renderAreaItems;
    private _renderLabelItems;
    protected render(): TemplateResult;
    private _loadSubEntries;
    private _filterExpanded;
    private _filterChanged;
    private _batteryEntity;
    private _batteryChargingEntity;
    private _handleRowClicked;
    private _handleSearchChange;
    private _addDevice;
    private _handleSelectionChanged;
    private _handleBulkArea;
    private _bulkAddArea;
    private _bulkCreateArea;
    private _handleBulkLabel;
    private _bulkLabel;
    private _bulkCreateLabel;
    private _deleteSelected;
    private _clearSelection;
    private _handleSortingChanged;
    private _handleGroupingChanged;
    private _handleCollapseChanged;
    private _handleColumnsChanged;
    private _handleBulkAction;
    static get styles(): CSSResultGroup;
}
declare global {
    interface HTMLElementTagNameMap {
        "ha-config-devices-dashboard": HaConfigDeviceDashboard;
    }
}
